namespace Solana.Unity.Dex.Orca.Core.Errors
{
    public enum WhirlpoolErrorType : uint
    {
        InvalidEnum = 6000U,
        InvalidStartTick = 6001U,
        TickArrayExistInPool = 6002U,
        TickArrayIndexOutofBounds = 6003U,
        InvalidTickSpacing = 6004U,
        ClosePositionNotEmpty = 6005U,
        DivideByZero = 6006U,
        NumberCastError = 6007U,
        NumberDownCastError = 6008U,
        TickNotFound = 6009U,
        InvalidTickIndex = 6010U,
        SqrtPriceOutOfBounds = 6011U,
        LiquidityZero = 6012U,
        LiquidityTooHigh = 6013U,
        LiquidityOverflow = 6014U,
        LiquidityUnderflow = 6015U,
        LiquidityNetError = 6016U,
        TokenMaxExceeded = 6017U,
        TokenMinSubceeded = 6018U,
        MissingOrInvalidDelegate = 6019U,
        InvalidPositionTokenAmount = 6020U,
        InvalidTimestampConversion = 6021U,
        InvalidTimestamp = 6022U,
        InvalidTickArraySequence = 6023U,
        InvalidTokenMintOrder = 6024U,
        RewardNotInitialized = 6025U,
        InvalidRewardIndex = 6026U,
        RewardVaultAmountInsufficient = 6027U,
        FeeRateMaxExceeded = 6028U,
        ProtocolFeeRateMaxExceeded = 6029U,
        MultiplicationShiftRightOverflow = 6030U,
        MulDivOverflow = 6031U,
        MulDivInvalidInput = 6032U,
        MultiplicationOverflow = 6033U,
        InvalidSqrtPriceLimitDirection = 6034U,
        ZeroTradableAmount = 6035U,
        AmountOutBelowMinimum = 6036U,
        AmountInAboveMaximum = 6037U,
        TickArraySequenceInvalidIndex = 6038U,
        AmountCalcOverflow = 6039U,
        AmountRemainingOverflow = 6040U
    }
}